[package]
name = "day-18-like-a-gif-for-your-yard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
overflow-checks = false